### ISSUE TITLE
Unable to find `text_summarize` folder

### ISSUE THREAD

**Issue by v-jiaodi** [Azure-Samples/function-python-ai-openai-chatgpt#3]
**Describe the issue:**
Unable to find `text_summarize` folder. 

![image](https://github.com/Azure-Samples/function-python-ai-openai-chatgpt/assets/80496810/7db80e27-f7a0-49a2-8155-c6c9655f68a3)

The following samples also have this issue：
https://github.com/Azure-Samples/function-csharp-ai-openai-chatgpt
https://github.com/Azure-Samples/function-javascript-ai-openai-chatgpt

**Suggestion:** 
Update `text_summarize` to `root`  folder in README.md.

@hemarina for notification.

**Comment by paulyuk** [comment]
fixed by #3
