### ISSUE TITLE
`func start` need to connect a machine

### ISSUE THREAD

**Issue by v-jiaodi** [Azure-Samples/function-python-ai-openai-chatgpt#4]
**Describe the issue:**
When executing `func start` according to [README.md](https://github.com/Azure-Samples/function-python-ai-openai-chatgpt#readme), the error is as follows:

![image](https://github.com/Azure-Samples/function-python-ai-openai-chatgpt/assets/80496810/b4945097-fabc-4a7b-a8c9-042267923b6f)

**Repro Steps:**
1. Clone the code to local.
2.  Set the System Variables **OPENAI_API_KEY**.
3. Add this local.settings.json file to the root folder. 
4. Run `pip3 install -r requirements.txt` and `func start`.

**Environment:**
- OS: Windows desktop.

**Expected behavior:**
 Run `func start` can pass.

@hemarina for notification.

**Comment by paulyuk** [comment]
I see.  That error message is telling you that you're trying to connect to the storage emulator, but that is not running.  I will add a readme step for `docker run -p 10000:10000 -p 10001:10001 -p 10002:10002 mcr.microsoft.com/azure-storage/azurite`.

**Comment by paulyuk** [comment]
Given this is an HTTP trigger, an even simpler change is to set the storage connection string to empty/null, and that's safe because we don't need it yet.  

```json
    "AzureWebJobsStorage": "",
```
 in local.settings.json.  I'm going to PR the change right now.

**Comment by paulyuk** [comment]
fixed by #3
